#!/usr/bin/perl
use strict;
use warnings;

sub backup($@);

my $IPMAGIC_NAME = "sx";
my $BASE_DIR = "$ENV{HOME}/Code/sx";

my $USAGE = "Usage:
  $0 -h|--help
    show this message

  $0 [OPTS]
    run backups

  OPTS
    -q | --quick | quick
      skip maintenance backups and run backups only
        -skip backup-comm apply and cleanup (still include fetch)
        -skip cleanup-connman
        -skip check-missing in dcim-backup
        -skip sync-pixmirror
        -skip cleanup-backups
        -skip sync-home-config
";

sub main(@){
  my $opts = {
    quick => 0,
  };
  while(@_ > 0){
    my $arg = shift @_;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^(-q|--quick|quick)$/){
      $$opts{quick} = 1;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  print "making sure $IPMAGIC_NAME is ssh-able\n";
  system "ipmagic", $IPMAGIC_NAME, "-s", "echo found sx!\n";
  die "failed" if $? != 0;

  backup "backup-comm", "--cleanup-only" unless $$opts{quick};
  backup "backup-comm", "--fetch-only";
  backup "cleanup-connman" unless $$opts{quick};
  backup "dcim-backup", ($$opts{quick} ? ("--quick") : ());
  backup "sync-pixmirror" unless $$opts{quick};
  #backup "sync-android-apps --backup"; WAYDROID
  backup "backup-workouts";
  backup "backup-amazfish";
  backup "backup-hrmon";
  backup "backup-home";
  backup "backup-notes";
  backup "backup-klomp-lists";
  backup "cleanup-backups" unless $$opts{quick};
  backup "backup-tmobile-digits";
  backup "sync-home-config" unless $$opts{quick};
  backup "backup-comm", "--apply-only" unless $$opts{quick};
}

sub backup($@){
  my ($backupScript, @args) = @_;

  my $argFmt = @args > 0 ? " @args" : "";
  print "\n\n\n=========$backupScript$argFmt\n";
  system "$BASE_DIR/$backupScript", @args;

  die "$backupScript failed" if $? != 0;
}

&main(@ARGV);
