#!/usr/bin/perl
use strict;
use warnings;

my $user = "nemo";
my $ipmagicName = "sx";

my $BASE_DIR = "$ENV{HOME}/Code/sx";
my $BACKUP_DIR = "$BASE_DIR/backup/backup-lap";

my $SRC_DIR = "/home/$user/.cache/lap";

sub run(@);

sub main(@){
  my $rootUser = "root";

  run "mkdir -p $BACKUP_DIR" if not -d $BACKUP_DIR;
  die "ERROR: $BACKUP_DIR is not a dir\n" if not -d $BACKUP_DIR;

  my @cmd = ("ipmagic", $ipmagicName, "-u", $rootUser, "--rsync",
    "-avP",
    "--one-file-system",
    ":$SRC_DIR/",
    "$BACKUP_DIR/",
  );

  run @cmd;
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
