#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;

my $USER = "nemo";
my $ROOT_USER = "root";
my $IPMAGIC_NAME = "sx";

my $BASE_DIR = "$ENV{HOME}/Code/sx";
my $BACKUP_DIR = "$BASE_DIR/backup/backup-lap";

my $SRC_DIR = "/home/$USER/.cache/lap";

sub backupDir($$);
sub run(@);

sub main(@){
  backupDir($SRC_DIR, $BACKUP_DIR);
}

sub backupDir($$){
  my ($srcDir, $backupDir) = @_;
  run "mkdir -p $backupDir" if not -d $backupDir;
  die "ERROR: $backupDir is not a dir\n" if not -d $backupDir;

  runRetry 5, "ipmagic", $IPMAGIC_NAME, "mkdir -p $srcDir";

  my @cmd = ("ipmagic", $IPMAGIC_NAME, "-u", $ROOT_USER, "--rsync",
    "-avP",
    "--one-file-system",
    ":$srcDir/",
    "$backupDir/",
  );

  runRetry 5, @cmd;
}

&main(@ARGV);
