#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;

my $user = "nemo";
my $ipmagicName = "sx";

my $BASE_DIR = "$ENV{HOME}/Code/sx";
my $BACKUP_HOME_DIR = "$BASE_DIR/backup/backup-home";
my $BACKUP_BASH_HIST_DIR = "$BASE_DIR/backup/backup-bash-history";

my @excludes = qw(
  .cache/org.nemomobile/thumbnails/
  .cache/tracker/
  .cache/qtcmdplayer/

  .local/share/commhistory/
  .local/share/waydroid/

  android_storage/DCIM/OpenCamera

  Pictures/Camera
  Pictures/AdvancedCam
  Pictures/Screenshots
  Videos/Camera
  Videos/AdvancedCam

  Backgrounds/

  Code/
);

sub main(@){
  my $rootUser = "root";

  my @cmd = ("ipmagic", $ipmagicName, "-u", $rootUser, "--rsync",
    "-avP",
    "--del",
    "--one-file-system",
    ":/home/$user/",
    "$BACKUP_HOME_DIR/",
  );

  for my $exclude(@excludes){
    @cmd = (@cmd, "--exclude=$exclude");
  }

  run @cmd;

  print "\n\n";
  my $nowMillis = nowMillis();
  run "cp", "-ar",
    "$BACKUP_HOME_DIR/.bash_history",
    "$BACKUP_BASH_HIST_DIR/bash-history-$nowMillis";
}

&main(@ARGV);
