#!/usr/bin/perl
use strict;
use warnings;

my $user = "nemo";
my $ipmagicName = "sx";

my $BASE_DIR = "$ENV{HOME}/Code/sx";
my $BACKUP_DIR = "$BASE_DIR/backup/backup-home";

my @excludes = qw(
  .cache/org.nemomobile/thumbnails/
  .cache/tracker/
  .cache/qtcmdplayer/

  .local/share/commhistory/

  Backgrounds/

  Code/
);

sub run(@);

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  my $rootUser = "root";

  my @cmd = ("rsync",
    "-avP",
    "--del",
    "--one-file-system",
    "$rootUser\@$host:/home/$user/",
    "$BACKUP_DIR/",
  );

  for my $exclude(@excludes){
    @cmd = (@cmd, "--exclude=$exclude");
  }

  run @cmd;
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
