#!/usr/bin/perl
use strict;
use warnings;

sub backup($);

my $IPMAGIC_NAME = "sx";
my $BASE_DIR = "$ENV{HOME}/Code/sx";

my $USAGE = "Usage:
  $0 -h|--help
    show this message

  $0 [OPTS]
    run backups

  OPTS
";

sub main(@){
  my $opts = {
  };
  while(@_ > 0){
    my $arg = shift @_;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  print "making sure $IPMAGIC_NAME is ssh-able\n";
  system "ipmagic", $IPMAGIC_NAME, "-s", "echo found sx!\n";
  die "failed" if $? != 0;

  backup "cleanup-connman";
  backup "dcim-backup";
  backup "sync-pixmirror";
  #backup "sync-android-apps --backup"; WAYDROID
  backup "backup-lap";
  backup "backup-amazfish";
  backup "backup-hrmon";
  backup "backup-home";
  backup "backup-notes";
  backup "backup-klomp-lists";
  backup "cleanup-backups";
  backup "backup-tmobile-digits";
  backup "backup-comm";
}

sub backup($){
  my $backupScript = shift;

  print "\n\n\n=========$backupScript\n";
  system "$BASE_DIR/$backupScript";

  die "$backupScript failed" if $? != 0;
}

&main(@ARGV);
