#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";

my $okTypes = join "|", qw(boing bin remove all);

sub main(@){
  my $backupOnlyMode = 0;
  if(@_ > 0 and $_[0] =~ /^(--backup-only)$/){
    shift;
    $backupOnlyMode = 1;
  }

  my $type;
  if(@_ == 0){
    $type = "all";
  }elsif(@_ == 1 and $_[0] =~ /^($okTypes)$/){
    $type = $_[0];
  }else{
    die "Usage: $0 [--backup-only] [$okTypes]\n";
  }

  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  my $src = 'CONFIG_FILES';
  my $dest = '/opt/CONFIG_FILES';

  system 'rsync',
    '-a', '--no-owner', '--no-group',
    '--del',
    '-v', '--progress',
    "$src/", "root\@$host:$dest";

  system 'ssh', "root\@$host", "chown root.root -R $dest";

  my $args = $backupOnlyMode ? "--backup-only $type" : "$type";
  system 'ssh', "root\@$host", "$dest/config-overwrite.pl $args";
}

&main(@ARGV);
