#!/usr/bin/perl
use strict;
use warnings;

my $IPMAGIC_NAME = "sx";

my $REPO_URL = "https://github.com/GNOME/adwaita-icon-theme";
my $REPO_DIR = "$ENV{HOME}/Code/adwaita-icon-theme";

sub run(@);

sub main(@){
  if(-d $REPO_DIR){
    run "cd $REPO_DIR && git pull";
    if($? != 0){
      die "could not update $REPO_DIR";
    }
  }else{
    run "mkdir", "-p", $REPO_DIR;
    run "git", "clone", $REPO_URL, "$REPO_DIR/.";
    die "could not clone $REPO_URL" if $? != 0;
  }

  my $attempts = 3;
  my $success = 0;
  while($attempts > 0){
    run "pixmirror", "--size=128x128", "--trim-ext", "--png", "$REPO_DIR/Adwaita", "$REPO_DIR/128x128";
    $attempts -= 1;

    if($? == 0){
      $success = 1;
      last;
    }
  }

  if(not $success){
    die "ERROR: pixmirror failed\n";
  }

  run "ipmagic", $IPMAGIC_NAME, "-u", "root", "mkdir", "/usr/share/icons/Adwaita";

  run "ipmagic", $IPMAGIC_NAME, "-u", "root", "--rsync",
    "-avP",
    "--del",
    "--exclude=pixmirror-info",
    "$REPO_DIR/128x128/",
    ":/usr/share/icons/Adwaita/128x128";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
