#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";

sub run(@);

my $expect = '
set timeout -1

spawn pkill packagekitd

spawn zypper install pyqt

expect "Solution 2: break pyqt" {
  expect "Choose from above solutions by number"
  send -- "2\n"
}

expect "Continue?"
send -- "y\n"

expect eof
';

sub main(@){
  my $expectLibSrc = "/usr/lib/tcl/expect5.45+mer1/libexpect5.45.so";
  my $expectLibDest = "/usr/lib/libexpect5.45.so";

  run "ipmagic", $ipmagicName, "-u", "root",
    "ln -s $expectLibSrc $expectLibDest";

  run "ipmagic", $ipmagicName, "-u", "root",
    "expect <<HEREDOC\n$expect\nHEREDOC";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
