#!/usr/bin/perl
use strict;
use warnings;
use File::Basename qw(basename);

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my $SRC_DIR = "$ENV{HOME}/Code/sx/apks",
my $DEST_DIR_SD = "/media/sdcard/phone/apks-aliendalvik4";
my $DEST_DIR_HOME = "/home/nemo/apks";

my $EXEC = basename $0;

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message

  $EXEC [OPTS]
    install all apks in $SRC_DIR

  $EXEC [OPTS] PREFIX
    install all apks in $SRC_DIR with filename starting with PREFIX
    (all APK files are copied to the phone first, not just PREFIX*)

  OPTS
    --home
      use $DEST_DIR_HOME instead of $DEST_DIR_SD
";

sub run(@);

sub main(@){
  my $prefix = undef;
  my $destDir = $DEST_DIR_SD;
  while(@_ > 0){
    my $arg = shift @_;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^(--home)$/){
      $destDir = $DEST_DIR_HOME;
    }elsif($arg =~ /^[a-zA-Z0-9]/){
      die "$USAGE\nERROR: only one PREFIX allowed\n" if defined $prefix;
      $prefix = $arg;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  $prefix = "" if not defined $prefix;

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;
  die "could not find host\n" if $host !~ /\w/;

  run "apk-name", glob "$SRC_DIR/*";
  if($? != 0){
    die "ERROR: apk-name exited with non-zero code\n";
  }

  run "rsync", "-avP", "--del", "$SRC_DIR/", "$USER\@$host:$destDir/";

  run "ipmagic", $IPMAGIC_NAME, "-u", "root",
    "apkd-install-preload $destDir/$prefix*.apk";
  run "ipmagic", $IPMAGIC_NAME,
    "apkd-install $destDir/$prefix*.apk";

  print "\n\nignore the installation UIs\n";
  print "just watch each app install on its own in order, and then close the UIs\n";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
