#!/usr/bin/perl
use strict;
use warnings;

my $IPMAGIC_NAME = "sx";

my $REPO_URL = "https://github.com/GNOME/adwaita-icon-theme";
my $REPO_DIR = "$ENV{HOME}/Code/adwaita-icon-theme";

sub run(@);

sub main(@){
  if(-d $REPO_DIR){
    run "cd $REPO_DIR && git pull";
    if($? != 0){
      die "could not update $REPO_DIR";
    }
  }else{
    run "mkdir", "-p", $REPO_DIR;
    run "git", "clone", $REPO_URL, "$REPO_DIR/.";
    die "could not clone $REPO_URL" if $? != 0;
  }


  run "ipmagic", $IPMAGIC_NAME, "-u", "root", "--rsync", "-avP", "--del",
    "$REPO_DIR/Adwaita/", ":/usr/share/icons/Adwaita/";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
