#!/usr/bin/perl
use strict;
use warnings;

# hold these packages
my @PACKAGES_TO_LOCK = qw();

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my $SRC_DIR = "$ENV{HOME}/Code/sx/rpms",
my $DEST_DIR_SDCARD = "/media/sdcard/phone/rpms";
my $DEST_DIR_HOME = "/home/nemo/rpms";

my $usage = "Usage:
  $0 -h | --help
    show this message

  $0 [OPTS] [RPM_GLOB_PATTERN]
    -copy $SRC_DIR to $DEST_DIR_SDCARD
    -run pkcon -y install-local $DEST_DIR_SDCARD/*RPM_GLOB_PATTERN*.rpm
    -add a package hold to zypper for the following packages: @PACKAGES_TO_LOCK

  RPM_GLOB_PATTERN
    only install packages that match \"*RPM_GLOB_PATTERN*.rpm\"
    defaults to empty, i.e.: all packages

  OPTS
    --home
      use $DEST_DIR_HOME instead of $DEST_DIR_SDCARD
";

sub main(@){
  my $destDir = $DEST_DIR_SDCARD;
  my $rpmGlobPattern = undef;
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $usage;
      exit 0;
    }elsif($arg =~ /^(--home)$/){
      $destDir = $DEST_DIR_HOME;
    }elsif(not defined $rpmGlobPattern){
      $rpmGlobPattern = $arg;
    }else{
      die "$usage\nERROR: unknown arg $arg\n";
    }
  }

  $rpmGlobPattern = "" if not defined $rpmGlobPattern;

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;
  die "could not find host\n" if $host !~ /\w/;

  system "rsync", "-avP", "--del", "$SRC_DIR/", "$USER\@$host:$destDir/";

  my $fullRpmGlobPath = "$destDir/*$rpmGlobPattern*.rpm";

  system "ipmagic", $IPMAGIC_NAME, "-u", "root", "pkcon -y install-local $fullRpmGlobPath";

  for my $pkg(@PACKAGES_TO_LOCK){
    system "ipmagic", $IPMAGIC_NAME, "-u", "root", "zypper addlock $pkg";
  }
}

&main(@ARGV);
