#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;

use File::Basename qw(basename);

my $IPMAGIC_NAME = "sx";
my $ROOT_USER = "root";

my @MODULES_ARR = (
  qtemail => [qw(
    Net::SSLeay
    Mail::IMAPClient
    IO::Socket::SSL
    Date::Parse
    MIME::Lite
    MIME::Parser
    Encode::HanExtra
  )],
  klompbigtext => [qw(
    Text::CSV
  )],
  robinhood => [qw(
    JSON
  )],
  tasmota => [qw(
    Parallel::ForkManager
  )],
  utils => [qw(
    DBI
    DBD::SQLite
    DateTime
    XML::LibXML
    Cpanel::JSON::XS
  )],
);
my %MODULES = @MODULES_ARR;
my @GROUP_NAMES = map {$MODULES_ARR[$_]} grep {$_ % 2 == 0} (0..$#MODULES_ARR);
my $GROUP_NAME_REGEX = join "|", @GROUP_NAMES;

my $MODULES_FORMAT = join('', map {"    $_ => @{$MODULES{$_}}\n"} @GROUP_NAMES);

my $EXEC = basename $0;

my $USAGE = "Usage:
  $EXEC [MODULE_GROUP MODULE_GROUP ..]
    install cpan module groups indicated
      (default is to install all if none are given)

    \n$MODULES_FORMAT
";

sub main(@){
  my @groups;
  while(@_ > 0){
    my $arg = shift @_;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^($GROUP_NAME_REGEX)$/){
      push @groups, $arg;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  @groups = @GROUP_NAMES if @groups == 0;

  if(not ipmagicTest($IPMAGIC_NAME, $ROOT_USER, "-x", "/usr/local/bin/cpanm")){
    ipmagicRun $IPMAGIC_NAME, $ROOT_USER, "curl -L https://cpanmin.us | perl - --sudo App::cpanminus";
    if(not ipmagicTest($IPMAGIC_NAME, $ROOT_USER, "-x", "/usr/local/bin/cpanm")){
      die "ERROR: cpanminus is not installed\n";
    }
  }

  for my $group(@groups){
    die "ERROR: unknown group\n" if not defined $MODULES{$group};
    my @modules = @{$MODULES{$group}};

    print "\n##### installing $group\n#####   @modules\n";
    ipmagicRun $IPMAGIC_NAME, $ROOT_USER, "cpanm --notest --nointeractive @modules";
    print "\n\n";
  }

  #build encodings after install
  ipmagicRun $IPMAGIC_NAME, $ROOT_USER, "enc2xs", "-C";
}

&main(@ARGV);
