#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";
my $user = "nemo";

my $srcDir = "$ENV{HOME}/Code/sx/apks",
my $destDir = "/media/sdcard/phone/apks";

my $usage = "Usage:
  $0 -h|--help
    show this message

  $0
    install all apks in $srcDir

  $0 PREFIX
    install all apks in $srcDir with filename starting with PREFIX
    (all APK files are copied to the phone first, not just PREFIX*)
";

sub run(@);

sub main(@){
  my $prefix = "";
  if(@_ == 1 and $_[0] =~ /^(-h|--help)$/){
    print $usage;
    exit 0;
  }elsif(@_ == 1){
    $prefix = $_[0];
  }elsif(@_ > 0){
    die $usage;
  }

  my $host = `ipmagic $ipmagicName`;
  chomp $host;
  die "could not find host\n" if $host !~ /\w/;

  run "apk-name", glob "$srcDir/*";
  if($? != 0){
    die "ERROR: apk-name exited with non-zero code\n";
  }

  run "rsync", "-avP", "$srcDir/", "$user\@$host:$destDir/";

  run "ipmagic", $ipmagicName, "apkd-install $destDir/$prefix*.apk";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
