#!/usr/bin/perl
use strict;
use warnings;

# hold these packages
my @PACKAGES_TO_LOCK = qw(lipstick2vnc);

my $ipmagicName = "sx";
my $user = "nemo";

my $srcDir = "$ENV{HOME}/Code/sx/rpms",
my $destDir = "/media/sdcard/phone/rpms";
my $destDirHome = "/home/nemo/rpms";

my $usage = "Usage:
  $0 -h | --help
    show this message

  $0 [OPTS]
    -copy $srcDir to $destDir
    -run pkcon -y install-local $destDir/*.rpm

  OPTS
    --home
      use $destDirHome instead of $destDir
";

sub main(@){
  my $rpmGlobPattern = undef;
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $usage;
      exit 0;
    }elsif($arg =~ /^(--home)$/){
      $destDir = $destDirHome;
    }else{
      die "$usage\nERROR: unknown arg $arg\n";
    }
  }

  my $host = `ipmagic $ipmagicName`;
  chomp $host;
  die "could not find host\n" if $host !~ /\w/;

  system "rsync", "-avP", "--del", "$srcDir/", "$user\@$host:$destDir/";

  system "ipmagic", $ipmagicName, "-u", "root", "pkcon -y install-local $destDir/*.rpm";

  for my $pkg(@PACKAGES_TO_LOCK){
    system "ipmagic", $ipmagicName, "-u", "root", "zypper addlock $pkg";
  }
}

&main(@ARGV);
