#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";
my $user = "nemo";

my $srcDir = "$ENV{HOME}/Code/sx/rpms",
my $destDir = "/media/sdcard/phone/rpms";

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;
  die "could not find host\n" if $host !~ /\w/;

  system "rsync", "-avP", "$srcDir/", "$user\@$host:$destDir/";

  system "ipmagic", $ipmagicName, "-u", "root", "pkcon -y install-local $destDir/*.rpm";
}

&main(@ARGV);
