#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";

my $repo = "$ENV{HOME}/Code/sx/backup/backup-contacts/repo";

sub run(@);

sub main(@){
  my $user = "nemo";
  my $host = `ipmagic $ipmagicName`;
  die "failed to get host" if $? != 0;
  chomp $host;

  my $now = `date +'%Y-%m-%d_%s'`;
  chomp $now;

  my $vcfFile = "contacts-$now.vcf";

  run "scp", "$repo/contacts.vcf", "$user\@$host:/tmp/$vcfFile";
  run "ssh", "$user\@$host", "
    devel-su -p vcardconverter /tmp/$vcfFile && \
    echo success || ( echo FAILED TO PROCESS SQLITE DBS && exit 1 )
  ";
}

sub run(@){
  print "@_\n";
  system @_;
  die "FAILED: @_\n" if $? != 0;
}

&main(@ARGV);
