#!/usr/bin/perl
use strict;
use warnings;

my $user = "nemo";
my $ipmagicName = "sx";

my $BASE_DIR = "$ENV{HOME}/Code/sx";
my $BACKUP_DIR = "$BASE_DIR/backup/klomp";

sub run(@);

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  my $now = time;
  run "ipmagic", $ipmagicName, "rsync -avP /media/sdcard/phone/klomp/ /media/sdcard/phone/klomp-bak-$now";

  run "rsync", "-avP", "--del", "$BACKUP_DIR/latest/", "$user\@$host:/media/sdcard/phone/klomp/";

  print "REMEMBER TO RUN klomp-sync for db and datecache\n";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
