#!/usr/bin/perl
use strict;
use warnings;

my $repo = "$ENV{HOME}/Code/s5/backup/backup-contacts/repo";

sub run(@);

sub main(@){
  my $vcfFile = "contacts-" . time . ".vcf";
  run "adb", "push", "$repo/contacts.vcf", "/sdcard/$vcfFile";

  run "adb", "shell",
    "am",
    "start",
    "-t", "text/x-vcard",
    "-d", "file:///sdcard/$vcfFile",
    "-a", "android.intent.action.VIEW",
    "com.android.contacts",
    ;
}

sub run(@){
  print "@_\n";
  system @_;
  die "FAILED: @_\n" if $? != 0;
}

&main(@ARGV);
