#!/usr/bin/perl
use strict;
use warnings;

sub run(@){
  print "@_\n";
  system @_;
}

sub main(@){
  my $host = `s5`;
  chomp $host;
  my $user = "android";
  run "rsync", "-avP",
    "--exclude=status",
    "$ENV{HOME}/openvpn",
    "$user\@$host:/home/$user";
  run "rsync", "-avP", "$ENV{HOME}/.config/qtemail/", "$user\@$host:/home/$user/.config/qtemail/";
  run "scp", "$ENV{HOME}/.gpg", "$user\@$host:/home/$user";
  run "scp", "$ENV{HOME}/.twip", "$user\@$host:/home/$user";
  run "scp", "$ENV{HOME}/.secrets", "$user\@$host:/home/$user";

  run "s5", "
    cd /home/$user/openvpn
    rm client.pem client.pem.default
    ln -s client.pem.wolke-n9 client.pem
    ln -s client.pem.wolke-n9 client.pem.default
  ";
}

&main(@ARGV);
