#!/usr/bin/perl
use strict;
use warnings;

my $IPMAGIC_NAME = "sx";

my $CMDS = {
  "backup-daemon" => {sched=>"2h", timeout=>"30min", cmd=>"backup-remote"},
  "email-daemon" => {sched=>"30m", timeout=>"15min", cmd=>"/opt/qtemail/bin/email.pl --update --folder=inbox"},
  "networkfix-daemon" => {sched=>"10m", timeout=>"1min", cmd=>"network-fix --no-force --wait=5000"},
  "gps-mls-update-daemon" => {sched=>"8h", timeout=>"5min", cmd=>"gps-mls-update"},
};

sub main(@){
  system "ipmagic", $IPMAGIC_NAME, "timed-cmd", "--clear";
  print "\n\n\n";

  for my $title(sort keys %$CMDS){
    my $sched = $$CMDS{$title}{sched};
    my $timeout = $$CMDS{$title}{timeout};
    my $cmd = $$CMDS{$title}{cmd};

    my @daemonRunCmd = (
      "udo", "daemon-run",
      "--name=$title", "--timeout=$timeout",
      "--verbose",
      $cmd,
    );

    print "\n";
    system "ipmagic", $IPMAGIC_NAME,
      "timed-cmd --add $sched --title=$title --cmd='@daemonRunCmd'";
  }

  print "\n\n\n";
  system "ipmagic", $IPMAGIC_NAME, "timed-cmd", "--get";
}

&main(@ARGV);
