#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

my $IPMAGIC_NAME = "sx";

my $STARTUP_SCRIPT_FILE = "/usr/local/bin/autostart";
my $STARTUP_SCRIPT_CONTENTS = "#!/bin/sh
PATH=/home/nemo/bin:\$PATH

/home/nemo/bin/screen-daemon backup-daemon --start
/home/nemo/bin/screen-daemon email-daemon --start
/home/nemo/bin/screen-daemon button-monitor --start
sudo cpu-enable fast
aliendalvik-post-start
";

my @SYSTEMD_SYMLINKS = qw(
  /home/nemo/.config/systemd/user/auto-start.service
  /home/nemo/.config/systemd/user/user-session.target.wants/auto-start.service
);

my $SYSTEMD_SERVICE_FILE = "/usr/lib/systemd/user/auto-start.service";
my $SYSTEMD_SERVICE_CONTENTS = "[Unit]
Description=Auto-start stuff after lipstick
Requires=lipstick.service
After=lipstick.service

[Service]
Type=oneshot
ExecStart=$STARTUP_SCRIPT_FILE
RemainAfterExit=yes

[Install]
WantedBy=user-session.target
";

sub writeRemoteFile($$$$);

sub main(@){
  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  writeRemoteFile $host, "root", $STARTUP_SCRIPT_FILE, $STARTUP_SCRIPT_CONTENTS;
  system "ssh", "root\@$host", "
    chmod a+x $STARTUP_SCRIPT_FILE
    chown root.root $STARTUP_SCRIPT_FILE
  ";

  writeRemoteFile $host, "root", $SYSTEMD_SERVICE_FILE, $SYSTEMD_SERVICE_CONTENTS;
  system "ssh", "root\@$host", "
    chown nemo.nemo $SYSTEMD_SERVICE_FILE
  ";

  for my $symlink(@SYSTEMD_SYMLINKS){
    system "ssh", "nemo\@$host", "
      rm -f $symlink
      ln -s $SYSTEMD_SERVICE_FILE $symlink
    ";
  }
}

sub writeRemoteFile($$$$){
  my ($host, $userName, $destFile, $contents) = @_;
  my $tmpFile = "/tmp/$0-" . int(time * 1000.0);
  open FH, "> $tmpFile" or die "Could not write to $tmpFile\n";
  print FH $contents;
  close FH;
  system "rsync", "-avP", $tmpFile, "$userName\@$host:$destFile";
}

&main(@ARGV);
