#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;

use Cwd qw(abs_path);
use File::Basename qw(basename dirname);

sub getConf();

my $USER = "nemo";
my $IPMAGIC_NAME = "sx";

my $BASE_DIR = abs_path(dirname($0));

my $DIR_MODELS_LOCAL = "$BASE_DIR/backup/dsnote-models";
my $DIR_MODELS_REMOTE = "/home/$USER/dsnote-models";

my $FILE_CFG_REMOTE = "/home/$USER/.config/org.mkiol/dsnote/settings.conf";

my $CFG_GENERAL = {
};
my $CFG_SERVICE = {
};

my $EXEC = basename $0;

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message

  $EXEC
    -overwrite harbour-dsnote TTS+STT models local=>remote
    -create local tmp settings.conf file
    -overwrite remote config file
";

sub main(@){
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }else{
      die "ERROR: unknown arg $arg\n";
    }
  }

  ipmagicRun $IPMAGIC_NAME, $USER, "--rsync", "-avP", "--del",
    "$DIR_MODELS_LOCAL/", ":$DIR_MODELS_REMOTE",
  ;

  my $tmpCfgFile = "/tmp/dsnote-conf-" . nowMillis();
  writeFile $tmpCfgFile, getConf();

  my $cfgDir = dirname $FILE_CFG_REMOTE;
  ipmagicRun $IPMAGIC_NAME, $USER, "mkdir", "-p", "$cfgDir/";

  ipmagicRun $IPMAGIC_NAME, $USER, "--rsync", "-avP",
    $tmpCfgFile, ":$FILE_CFG_REMOTE",
  ;

  run "rm", $tmpCfgFile;
}

sub getConf(){
  my $confGeneral = {%$CFG_GENERAL};

  my $confSvc = {%$CFG_SERVICE};

  my $cfg = "";
  $cfg .= "[General]\n";
  for my $key(sort keys %$confGeneral){
    $cfg .= "$key=$$confGeneral{$key}\n";
  }
  $cfg .= "\n";
  $cfg .= "[service]\n";
  for my $key(sort keys %$confSvc){
    $cfg .= "$key=$$confSvc{$key}\n";
  }

  return $cfg;
}

&main(@ARGV);
