#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;
use File::Basename qw(basename);
use JSON qw(from_json);

sub parseXml($);
sub calculateXml();

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my $APP_DIR = "/home/.appsupport/instance/nemo/data/data/com.abitdo.advance";
my $SHARED_PREFS_DIR = "$APP_DIR/shared_prefs";
my $CFG_XML_FILE = "$SHARED_PREFS_DIR/MicroDatasArrays.xml";

my $XML_PREFIX = "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>\n"
  . "<map>\n"
  . "    <string name=\"MicroDatasArrays\">"
;
my $XML_SUFFIX = "</string>\n</map>\n";

my $PROFILES = {
  kingdom => {
    UP    => 'W',
    DOWN  => 'S',
    LEFT  => 'A',
    RIGHT => 'D',

    A     => 'A',
    B     => 'W',
    X     => 'S',
    Y     => 'D',

    L     => 'SHIFT',
    R     => 'K',
    L2    => 'ENTER',
    R2    => 'ENTER',

    MINUS => 'ESC',
    PLUS  => 'ENTER',
    STAR  => 'SHIFT',
    SYM   => 'ESC',

    UNK0  => 'NONE',
    UNK1  => 'NONE',
    UNK2  => 'NONE',
    UNK3  => 'NONE',
  },
};


my $KEY_MAPPINGS = {
  NONE  => 0,
  ENTER => 40,
  SHIFT => 225,
  ESC   => 41,
  (map {$_ => ord($_)-61} ("A".."Z")),  #A-Z => 4-29
};
my $KEY_NAMES_BY_ID = { map {$$KEY_MAPPINGS{$_} => $_} sort keys %$KEY_MAPPINGS };

my $BTN_TYPES = {
  UP    => 512,
  DOWN  => 256,
  LEFT  => 128,
  RIGHT => 64,
  A     => 8192,
  B     => 4096,
  X     => 16,
  Y     => 32,
  L     => 1024,
  R     => 2048,
  L2    => 16384,
  R2    => 32768,
  MINUS => 8,
  PLUS  => 1,
  STAR  => 123,
  SYM   => 124,
  UNK0  => 2,
  UNK1  => 4,
  UNK2  => 33554432,
  UNK3  => 67108864,
};
my $BTN_NAMES_BY_TYPE = { map {$$BTN_TYPES{$_} => $_} sort keys %$BTN_TYPES };

my @XML_BTN_ORDER = qw(
  A B X Y
  L R L2 R2
  UNK0 UNK1
  MINUS PLUS STAR SYM
  UP DOWN LEFT RIGHT
  UNK2 UNK3
);

my $EXEC = basename $0;

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message

  $EXEC -g | --get
    -fetch remote $IPMAGIC_NAME:$CFG_XML_FILE
    -parse profiles

  $EXEC -s | --set
    -generate XML from config
    -write remote $IPMAGIC_NAME:$CFG_XML_FILE
";

my $MODE_GET = "get";
my $MODE_SET = "set";

sub main(@){
  my $mode = undef;
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^(-g|--get)$/){
      $mode = $MODE_GET;
    }elsif($arg =~ /^(-s|--set)$/){
      $mode = $MODE_SET;
    }else{
      die "ERROR: unknown arg $arg\n";
    }
  }

  die "$USAGE\nERROR: missing mode\n" if not defined $mode;

  if($mode eq $MODE_GET){
    my $xml = readProc "ipmagic", $IPMAGIC_NAME, "-u", "root",
      "cat $CFG_XML_FILE",
    ;

    my @profiles = parseXml($xml);
    for my $profile(@profiles){
      printf "\n\n### PROFILE %s\n", $$profile{name};
      my %mappings = %{$$profile{mappings}};
      for my $btnName(@XML_BTN_ORDER){
        my @keyNames = @{$mappings{$btnName}};
        pop @keyNames while @keyNames > 0 and $keyNames[-1] eq "NONE";
        printf "  %-5s = %s\n", $btnName, join(" / ", @keyNames);
      }
    }
  }elsif($mode eq $MODE_SET){
    my $xml = calculateXml();
    my $tmpFile = "/tmp/8bitdo-" . nowMillis() . ".xml";
    writeFile($tmpFile, $xml);

    run "ipmagic", $IPMAGIC_NAME, "-u", "root", "-s", "
      if [ ! -d \"$SHARED_PREFS_DIR\" ] && [ -d \"$APP_DIR\" ] ; then
        mkdir -p $SHARED_PREFS_DIR
        chown --reference=$APP_DIR $SHARED_PREFS_DIR
      fi
    ";

    run "ipmagic", $IPMAGIC_NAME, "-u", "root", "--rsync",
      "-avP", "--no-owner", "--no-group",
      $tmpFile,
      ":$CFG_XML_FILE",
    ;
    run "ipmagic", $IPMAGIC_NAME, "-u", "root",
      "chown", "--reference=$SHARED_PREFS_DIR", $CFG_XML_FILE;

    run "rm", $tmpFile;
  }else{
    die "ERROR: unknown mode $mode\n";
  }
}

sub parseXml($){
  my ($xml) = @_;
  my $profileArrStr = undef;
  if($xml =~ /^\Q$XML_PREFIX\E(.*)\Q$XML_SUFFIX\E$/s){
    $profileArrStr = $1;
  }else{
    die "ERROR: malformed/missing XML at $CFG_XML_FILE:\n$xml\n";
  }
  $profileArrStr =~ s/&quot;/"/g;

  my @profiles;

  my @profileArr = @{from_json($profileArrStr)};
  for my $profile(@profileArr){
    my $profileName = $$profile{name};
    my $mappingArrStr = $$profile{data};
    $mappingArrStr =~ s/\\"/"/g;
    my @mappingArr = @{from_json($mappingArrStr)};
    my $keyMaps = {};
    for my $mapping(@mappingArr){
      my $btnType = $$mapping{type};
      my $btnName = $$BTN_NAMES_BY_TYPE{$btnType};
      if(not defined $btnName){
        die "ERROR: missing button type '$btnType' for XML:\n$xml";
      }
      my @keyIds = map {$$mapping{"mapping$_"}} (0, 1, 2, 3);
      my @keyNames = map {$$KEY_NAMES_BY_ID{$_}} @keyIds;
      @keyNames = grep {defined $_} @keyNames;
      if(@keyNames != 4){
        die "ERROR: missing mappings for key $btnName for XML:\n$xml\n";
      }
      $$keyMaps{$btnName} = [@keyNames];
    }
    for my $btnName(@XML_BTN_ORDER){
      if(not defined $$keyMaps{$btnName}){
        die "ERROR: missing mapping for button $btnName for XML\n$xml\n";
      }
    }
    push @profiles, {name=>$profileName, mappings=>$keyMaps};
  }

  return @profiles;
}

sub calculateXml(){
  my @profileJsonStrs;
  for my $profileName(sort keys %$PROFILES){
    my $profileKeys = $$PROFILES{$profileName};
    my @jsonMappings;
    for my $btnName(sort keys %$profileKeys){
      my $type = $$BTN_TYPES{$btnName};
      die "ERROR: unknown btn '$btnName' in '$profileName'\n" if not defined $type;
    }

    for my $btnName(@XML_BTN_ORDER){
      my $key = $$profileKeys{$btnName};
      my $type = $$BTN_TYPES{$btnName};
      my $mappingId = $$KEY_MAPPINGS{$key};
      die "ERROR: missing btn '$btnName' in '$profileName'\n" if not defined $key;
      die "ERROR: unknown key '$key' in '$profileName'\n" if not defined $mappingId;
      push @jsonMappings, "{\"mapping0\":$mappingId,\"mapping1\":0,\"mapping2\":0,\"mapping3\":0,\"type\":$type}";
    }

    #the json value is a string for some reason
    my $jsonMappingArrStr = "[" . join(",", @jsonMappings) . "]";
    $jsonMappingArrStr =~ s/"/\\"/g;

    my $json = "{\"data\":\"$jsonMappingArrStr\",\"name\":\"$profileName\"}";
    push @profileJsonStrs, $json;
  }

  my $xmlProfileStr = "[" . join(",", @profileJsonStrs) . "]";
  $xmlProfileStr =~ s/"/&quot;/g;

  return $XML_PREFIX . $xmlProfileStr . $XML_SUFFIX;
}

&main(@ARGV);
