#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

sub getConfig($);

sub getScaledFontSize();
sub getResMinDimension();
sub getConfigFileRemoteDir();
sub readRemoteConfigLines($);
sub writeRemoteConfigLines($@);
sub updateConfigLines($@);
sub run(@);

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my @CONFIG_FILE_REMOTE_DIRS = (
  "/home/$USER/android_storage/.cr3",
  "/home/$USER/.local/share/waydroid/data/media/0/.cr3",
);
my $CR3_INI_FILE = "cr3.ini";

my $usage = "Usage:
  $0 -h|--help
    show this message

  $0
  $0 --set
    find CONFIG_FILE_REMOTE_DIR:
      @CONFIG_FILE_REMOTE_DIRS
    update `ipmagic $IPMAGIC_NAME`:<CONFIG_FILE_REMOTE_DIR>$CR3_INI_FILE

  $0 -d|--diff|-n|--dryrun
    show what changes would be made by running --set
";

my @TAPZONES_SHORT = qw(
  PAGE_DOWN           PAGE_UP             PAGE_DOWN
  PAGE_UP             READER_MENU         PAGE_DOWN
  PAGE_UP             PAGE_DOWN           PAGE_DOWN
);
my @TAPZONES_LONG = qw(
  PAGE_UP             ZOOM_IN             PAGE_UP
  PAGE_DOWN           TOGGLE_ORIENTATION  PAGE_UP
  TTS_PLAY            ZOOM_OUT            PAGE_UP
);

my $LOW_RES_PX = 720;
my $HIGH_RES_PX = 1080;
my $FONT_SIZE_LOW_RES = 52;
my $FONT_SIZE_HIGH_RES = 84;

sub getConfig($){
  my ($fontSize) = @_;
  return {
    "app.browser.simple.mode"                                  => "1",
    "app.browser.sort.order"                                   => "FILENAME",

    "app.controls.doubletap.selection"                         => "0",

    "app.fullscreen"                                           => "1",

    "app.key.action.press.dbl.92"                              => "NONE",
    "app.key.action.press.dbl.93"                              => "NONE",
    "app.key.backlight.disabled"                               => "0",

    "app.motion.timeout"                                       => "0",
    "app.plugin.enabled.litres.org.coolreader.plugins.litres"  => "0",

    "app.screen.backlight.control.flick"                       => "0",
    "app.screen.backlight.day"                                 => "-1",
    "app.screen.backlight.lock.enabled"                        => "0",
    "app.screen.backlight"                                     => "100",
    "app.screen.orientation"                                   => "0",

    "app.settings.show.icons"                                  => "1",

    "app.tapzone.action.tap.1"                                 => $TAPZONES_SHORT[1-1],
    "app.tapzone.action.tap.2"                                 => $TAPZONES_SHORT[2-1],
    "app.tapzone.action.tap.3"                                 => $TAPZONES_SHORT[3-1],
    "app.tapzone.action.tap.4"                                 => $TAPZONES_SHORT[4-1],
    "app.tapzone.action.tap.5"                                 => $TAPZONES_SHORT[5-1],
    "app.tapzone.action.tap.6"                                 => $TAPZONES_SHORT[6-1],
    "app.tapzone.action.tap.7"                                 => $TAPZONES_SHORT[7-1],
    "app.tapzone.action.tap.8"                                 => $TAPZONES_SHORT[8-1],
    "app.tapzone.action.tap.9"                                 => $TAPZONES_SHORT[9-1],
    "app.tapzone.action.tap.long.1"                            => $TAPZONES_LONG[1-1],
    "app.tapzone.action.tap.long.2"                            => $TAPZONES_LONG[2-1],
    "app.tapzone.action.tap.long.3"                            => $TAPZONES_LONG[3-1],
    "app.tapzone.action.tap.long.4"                            => $TAPZONES_LONG[4-1],
    "app.tapzone.action.tap.long.5"                            => $TAPZONES_LONG[5-1],
    "app.tapzone.action.tap.long.6"                            => $TAPZONES_LONG[6-1],
    "app.tapzone.action.tap.long.7"                            => $TAPZONES_LONG[7-1],
    "app.tapzone.action.tap.long.8"                            => $TAPZONES_LONG[8-1],
    "app.tapzone.action.tap.long.9"                            => $TAPZONES_LONG[9-1],

    "app.touch.gesture.page.flipping"                          => "0",
    "app.touch.secondary.action.type"                          => "0",
    "app.trackball.disabled"                                   => "0",

    "app.ui.theme"                                             => "DARK",
    "background.color.day"                                     => "0xffffff",
    "background.color.default"                                 => "0x000000",
    "background.image"                                         => "(NONE)",

    "cr3.file.props.font.size"                                 => "22",

    "crengine.autosave.bookmarks"                              => "1",
    "crengine.bookmarks.icons"                                 => "0",
    "crengine.display.full.update.interval"                    => "1",
    "crengine.display.turbo.update"                            => "0",
    "crengine.doc.embedded.fonts.enabled"                      => "0",
    "crengine.doc.embedded.styles.enabled"                     => "1",
    "crengine.file.txt.preformatted"                           => "1",
    "crengine.font.size"                                       => $fontSize,
    "crengine.footnotes"                                       => "1",

    "crengine.highlight.bookmarks.color.comment.day"           => "0xaaaa55",
    "crengine.highlight.bookmarks.color.comment"               => "0xa09060",
    "crengine.highlight.bookmarks.color.correction.day"        => "0xc07070",
    "crengine.highlight.bookmarks.color.correction"            => "0x906060",
    "crengine.highlight.bookmarks.day"                         => "1",
    "crengine.highlight.selection.color.day"                   => "0xaaaaaa",
    "crengine.highlight.selection.color"                       => "0x808080",
    "crengine.hyphenation.dictionary.code"                     => "ENGLISH",
    "crengine.interline.space"                                 => "100",
    "crengine.night.mode"                                      => "1",
    "crengine.page.animation"                                  => "0",
    "crengine.page.header.chapter.marks"                       => "1",
    "crengine.page.header.font.color.day"                      => "0x000000",
    "crengine.page.header.font.color"                          => "0xffffff",
    "crengine.page.header.font.size"                           => "32",
    "crengine.page.margin.bottom"                              => "20",
    "crengine.page.margin.left"                                => "30",
    "crengine.page.margin.right"                               => "30",
    "crengine.page.margin.top"                                 => "20",
    "crengine.page.view.mode"                                  => "1",
    "crengine.progress.show.first.page"                        => "1",
    "crengine.style.floating.punctuation.enabled"              => "1",
    "crengine.style.space.condensing.percent"                  => "50",

    "font.color.day"                                           => "0x000000",
    "font.color.default"                                       => "0x00ff00",
    "font.face.weight.embolden"                                => "0",
    "font.gamma.day"                                           => "1.0",
    "font.kerning.enabled"                                     => "0",

    "styles.annotation.align"                                  => "text-align\\: justify",
    "styles.annotation.font-size"                              => "font-size\\: 90%",
    "styles.annotation.font-style"                             => "font-style\\: italic",
    "styles.annotation.margin-left"                            => "margin-left\\: 1em",
    "styles.annotation.margin-right"                           => "margin-right\\: 1em",
    "styles.annotation.text-indent"                            => "text-indent\\: 1.2em",
    "styles.cite.align"                                        => "text-align\\: justify",
    "styles.cite.font-style"                                   => "font-style\\: italic",
    "styles.cite.margin-bottom"                                => "margin-bottom\\: 0.3em",
    "styles.cite.margin-left"                                  => "margin-left\\: 1em",
    "styles.cite.margin-right"                                 => "margin-right\\: 1em",
    "styles.cite.margin-top"                                   => "margin-top\\: 0.3em",
    "styles.cite.text-indent"                                  => "text-indent\\: 1.2em",
    "styles.def.align"                                         => "text-align\\: justify",
    "styles.def.margin-bottom"                                 => "margin-bottom\\: 0em",
    "styles.def.margin-left"                                   => "margin-left\\: 0em",
    "styles.def.margin-right"                                  => "margin-right\\: 0em",
    "styles.def.margin-top"                                    => "margin-top\\: 0em",
    "styles.def.text-indent"                                   => "text-indent\\: 1.2em",
    "styles.epigraph.align"                                    => "text-align\\: justify",
    "styles.epigraph.font-style"                               => "font-style\\: italic",
    "styles.epigraph.margin-bottom"                            => "margin-bottom\\: 0.3em",
    "styles.epigraph.margin-left"                              => "margin-left\\: 15%",
    "styles.epigraph.margin-right"                             => "margin-right\\: 1em",
    "styles.epigraph.margin-top"                               => "margin-top\\: 0.3em",
    "styles.epigraph.text-indent"                              => "text-indent\\: 1.2em",
    "styles.footnote-link.align"                               => "",
    "styles.footnote-link.font-size"                           => "font-size\\: 70%",
    "styles.footnote-link.vertical-align"                      => "vertical-align\\: super",
    "styles.footnote-title.align"                              => "",
    "styles.footnote-title"                                    => "font-size\\: 110%",
    "styles.footnote"                                          => "font-size\\: 70%",
    "styles.link.text-decoration"                              => "text-decoration\\: underline",
    "styles.poem.align"                                        => "text-align\\: justify",
    "styles.poem.font-style"                                   => "font-style\\: italic",
    "styles.poem.margin-bottom"                                => "margin-bottom\\: 0.3em",
    "styles.poem.margin-left"                                  => "margin-left\\: 15%",
    "styles.poem.margin-right"                                 => "margin-right\\: 1em",
    "styles.poem.margin-top"                                   => "margin-top\\: 0.3em",
    "styles.poem.text-indent"                                  => "text-indent\\: 0em",
    "styles.pre.align"                                         => "text-align\\: justify",
    "styles.pre.font-face"                                     => "font-family\\: \"Courier New\", \"Courier\", monospace",
    "styles.pre.margin-bottom"                                 => "margin-bottom\\: 0em",
    "styles.pre.margin-left"                                   => "margin-left\\: 0em",
    "styles.pre.margin-right"                                  => "margin-right\\: 0em",
    "styles.pre.margin-top"                                    => "margin-top\\: 0em",
    "styles.pre.text-indent"                                   => "text-indent\\: 0em",
    "styles.subtitle.align"                                    => "text-align\\: center",
    "styles.subtitle.font-style"                               => "font-style\\: italic",
    "styles.subtitle.margin-bottom"                            => "margin-bottom\\: 0.2em",
    "styles.subtitle.margin-top"                               => "margin-top\\: 0.2em",
    "styles.subtitle.text-indent"                              => "text-indent\\: 0em",
    "styles.text-author.font-style"                            => "font-style\\: italic",
    "styles.text-author.font-weight"                           => "font-weight\\: bolder",
    "styles.text-author.margin-left"                           => "margin-left\\: 1em",
    "styles.title.align"                                       => "text-align\\: center",
    "styles.title.font-size"                                   => "font-size\\: 110%",
    "styles.title.font-weight"                                 => "font-weight\\: bolder",
    "styles.title.margin-bottom"                               => "margin-bottom\\: 0.3em",
    "styles.title.margin-left"                                 => "margin-left\\: 0em",
    "styles.title.margin-right"                                => "margin-right\\: 0em",
    "styles.title.margin-top"                                  => "margin-top\\: 0.3em",
    "styles.title.text-indent"                                 => "text-indent\\: 0em",

    "viewer.toolbar.appearance"                                => "0",
    "viewer.toolbar.fullscreen.hide"                           => "1",
    "viewer.toolbar.location2"                                 => "5",

    "window.status.battery.percent"                            => "1",
    "window.status.line"                                       => "0",
    "window.status.pos.page.number"                            => "1",
    "window.status.title"                                      => "1",
  };
}

sub main(@){
  if(@_ == 1 and $_[0] =~ /^(-h|--help)$/){
    print $usage;
  }elsif(@_ == 0 or (@_ == 1 and $_[0] =~ /^(--set)$/)){
    my $cfg = getConfig(getScaledFontSize());
    my $configFileRemoteDir = getConfigFileRemoteDir();
    my @configLines = readRemoteConfigLines($configFileRemoteDir);
    my @newConfigLines = updateConfigLines($cfg, @configLines);
    writeRemoteConfigLines($configFileRemoteDir, @newConfigLines);
  }elsif(@_ == 1 and $_[0] =~ /^(-d|--diff|-n|--dryrun)$/){
    my $cfg = getConfig(getScaledFontSize());
    my $configFileRemoteDir = getConfigFileRemoteDir();
    updateConfigLines($cfg, readRemoteConfigLines($configFileRemoteDir));
  }else{
    die $usage;
  }
}

sub getScaledFontSize(){
  my $resMinDim = getResMinDimension();

  my $scale = ($resMinDim - $LOW_RES_PX) / ($HIGH_RES_PX - $LOW_RES_PX);
  my $fontSize = $scale*($FONT_SIZE_HIGH_RES - $FONT_SIZE_LOW_RES) + $FONT_SIZE_LOW_RES;
  return $fontSize;
}

sub getResMinDimension(){
  my $resMin = `ipmagic $IPMAGIC_NAME res --min-dimension`;
  chomp $resMin;
  if($resMin !~ /^\d+$/){
    die "ERROR: `res` command failed\n";
  }
  return $resMin;
}

sub getConfigFileRemoteDir(){
  my @lines = `ipmagic $IPMAGIC_NAME ls -d @CONFIG_FILE_REMOTE_DIRS 2>/dev/null`;
  for my $line(@lines){
    for my $dir(@CONFIG_FILE_REMOTE_DIRS){
      if($line =~ /^$dir\/?$/){
        return $dir;
      }
    }
  }
  die "ERROR: no config file dirs exist\n@CONFIG_FILE_REMOTE_DIRS\n";
}

sub readRemoteConfigLines($){
  my ($configFileRemoteDir) = @_;
  my @cmd = ("ipmagic", $IPMAGIC_NAME, "cat", "$configFileRemoteDir/$CR3_INI_FILE");
  open CMD, "-|",  @cmd or die "ERROR: @cmd failed\n$!\n";
  my @lines = <CMD>;
  close CMD;
  return @lines;
}

sub writeRemoteConfigLines($@){
  my ($configFileRemoteDir, @lines) = @_;
  my $nowMillis = int(time * 1000.0 + 0.5);
  my $tmpFile = "/tmp/coolreader-$nowMillis-cr3.ini";

  open FH, "> $tmpFile" or die "could not write $tmpFile\n$!\n";
  print FH @lines;
  close FH;

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  run "ipmagic", $IPMAGIC_NAME, "mkdir -p $configFileRemoteDir";
  run "scp", $tmpFile, "$USER\@$host:$configFileRemoteDir/$CR3_INI_FILE";

  run "rm", $tmpFile;
}

sub updateConfigLines($@){
  my ($cfg, @configLines) = @_;

  my @newConfigLines = (@configLines);
  for my $key(sort keys %$cfg){
    my $val = $$cfg{$key};

    my $found = 0;
    for my $line(@newConfigLines){
      if($line =~ /^\s*\Q$key\E\s*=\s*(.*)$/){
        my $oldVal = $1;
        if($oldVal ne $val){
          printf "%-40s: %s => %s\n", $key, $oldVal, $val;
        }

        $line = "$key=$val\n";
        $found = 1;
        last;
      }
    }

    if(not $found){
      printf "%-40s: %s => %s\n", $key, "<MISSING>", $val;
      push @newConfigLines, "$key=$val\n";
    }
  }
  return @newConfigLines;
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
