#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;
use File::Basename qw(dirname);

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my @SYMLINKS_ARR = (
  ["1qtemail",  "/media/sdcard/phone/email",   "/home/$USER/.cache/email"],
  ["2alarms",   "/media/sdcard/phone/alarms",  "/usr/share/alarms"],
  ["3sounds",   "/media/sdcard/phone/sounds",  "/usr/share/sounds/custom"],
  ["4klomp",    "/media/sdcard/phone/klomp",   "/home/$USER/.klomp"],
  ["5bashrc",   ".bashrc",                     "/home/$USER/.profile"],
  ["6vnclib",   "libvncserver.so.1",           "/usr/lib64/libvncserver.so.0"],
  ["7rootbin",  "/home/$USER/bin/",            "/root/bin"],
);
my %SYMLINKS = map {$$_[0] => {src => $$_[1], dest => $$_[2]}} @SYMLINKS_ARR;
my @SYMLINK_NAMES = map {$$_[0]} @SYMLINKS_ARR;

my $SYMLINKS_FORMAT = join '', map {sprintf "    %-10s: %-32s => %s\n", @$_} @SYMLINKS_ARR;

my $USAGE = "Usage:
  $0 [SYMLINK_NAME SYMLINK_NAME..]
    create + set user for the indicated symlink entries (or all if none given)
      -run as <USER> for dest files that start with /home/<USER>, run as root otherwise
      -delete dest file or dir if it exists
      -create symlinks as ln -s <SRC> <DEST>
    \n$SYMLINKS_FORMAT
";

sub main(@){
  my @names;
  while(@_ > 0){
    my $arg = shift @_;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif(defined $SYMLINKS{$arg}){
      push @names, $arg;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  @names = @SYMLINK_NAMES if @names == 0;

  for my $name(@names){
    my $sym = $SYMLINKS{$name};
    my ($src, $dest) = ($$sym{src}, $$sym{dest});
    my $destDir = dirname $$sym{dest};

    my $cmd = "rmdir $dest 2>/dev/null ; rm -f $dest && ln -s $src $dest";

    my $ipmagicUser = $destDir =~ /^\/home\/(\w+)(?:\/.*)?$/ ? "$1" : "root";

    run "ipmagic", $IPMAGIC_NAME, "-u", $ipmagicUser, "sh -c \"$cmd\"";
  }
}

&main(@ARGV);
