#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

sub run(@);

my $ipmagicName = "sx";
my $user = "nemo";

my $configFileRemote = "/home/$user/android_storage/.cr3/cr3.ini";

my @TAPZONES_SHORT = qw(
  PAGE_DOWN           PAGE_UP             PAGE_DOWN
  PAGE_UP             READER_MENU         PAGE_DOWN
  PAGE_UP             PAGE_DOWN           PAGE_DOWN
);
my @TAPZONES_LONG = qw(
  PAGE_UP             ZOOM_IN             PAGE_UP
  PAGE_DOWN           TOGGLE_ORIENTATION  PAGE_UP
  PAGE_DOWN           ZOOM_OUT            PAGE_UP
);

my %config = (
  "app.tapzone.action.tap.1"                                 => $TAPZONES_SHORT[1-1],
  "app.tapzone.action.tap.2"                                 => $TAPZONES_SHORT[2-1],
  "app.tapzone.action.tap.3"                                 => $TAPZONES_SHORT[3-1],
  "app.tapzone.action.tap.4"                                 => $TAPZONES_SHORT[4-1],
  "app.tapzone.action.tap.5"                                 => $TAPZONES_SHORT[5-1],
  "app.tapzone.action.tap.6"                                 => $TAPZONES_SHORT[6-1],
  "app.tapzone.action.tap.7"                                 => $TAPZONES_SHORT[7-1],
  "app.tapzone.action.tap.8"                                 => $TAPZONES_SHORT[8-1],
  "app.tapzone.action.tap.9"                                 => $TAPZONES_SHORT[9-1],
  "app.tapzone.action.tap.long.1"                            => $TAPZONES_LONG[1-1],
  "app.tapzone.action.tap.long.2"                            => $TAPZONES_LONG[2-1],
  "app.tapzone.action.tap.long.3"                            => $TAPZONES_LONG[3-1],
  "app.tapzone.action.tap.long.4"                            => $TAPZONES_LONG[4-1],
  "app.tapzone.action.tap.long.5"                            => $TAPZONES_LONG[5-1],
  "app.tapzone.action.tap.long.6"                            => $TAPZONES_LONG[6-1],
  "app.tapzone.action.tap.long.7"                            => $TAPZONES_LONG[7-1],
  "app.tapzone.action.tap.long.8"                            => $TAPZONES_LONG[8-1],
  "app.tapzone.action.tap.long.9"                            => $TAPZONES_LONG[9-1],
);

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  my $nowMillis = int(time * 1000.0 + 0.5);
  my $tmpFileOrig = "/tmp/coolreader-$nowMillis-orig.ini";
  my $tmpFileMod = "/tmp/coolreader-$nowMillis-mod.ini";

  run "scp", "$user\@$host:$configFileRemote", $tmpFileOrig;

  my @lines;
  if(-f $tmpFileOrig){
    open FH, "< $tmpFileOrig" or die "could not read $tmpFileOrig\n$!\n";
    @lines = <FH>;
    close FH;
  }

  for my $key(sort keys %config){
    my $val = $config{$key};

    my $found = 0;
    for my $line(@lines){
      if($line =~ /^\s*\Q$key\E\s*=/){
        $line = "$key=$val\n";
        $found = 1;
        last;
      }
    }

    if(not $found){
      push @lines, "$key=$val\n";
    }
  }

  open FH, "> $tmpFileMod" or die "could not write $tmpFileMod\n$!\n";
  print FH @lines;
  close FH;

  run "scp", $tmpFileMod, "$user\@$host:$configFileRemote";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
