#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;
use File::Basename qw(dirname);

my $IPMAGIC_NAME = "sx";

my $USER = "nemo";

my @SYMLINKS_ARR = (
  ["1qtemail",  "/media/sdcard/phone/email",   "/home/$USER/.cache/email"],
  ["2alarms",   "/media/sdcard/phone/alarms",  "/usr/share/alarms"],
  ["3sounds",   "/media/sdcard/phone/sounds",  "/usr/share/sounds/custom"],
  ["4klomp",    "/media/sdcard/phone/klomp",   "/home/$USER/.klomp"],
  ["5bashrc",   ".bashrc",                     "/home/$USER/.profile"],
  ["6vnclib",   "libvncserver.so.1",           "/usr/lib64/libvncserver.so.0"],
  ["7rootbin",  "/home/$USER/bin/",            "/root/bin"],
);
my %SYMLINKS = map {$$_[0] => {src => $$_[1], dest => $$_[2]}} @SYMLINKS_ARR;
my @SYMLINK_NAMES = map {$$_[0]} @SYMLINKS_ARR;

my $SYMLINKS_FMT = join '', map {"    $$_[0]: $$_[1] => $$_[2]\n"} @SYMLINKS_ARR;

my $USAGE = "Usage:
  $0 [SYMLINK_NAME ..]
    set up symlinks for the indicated symlink names
      (default is to set up all if none are given)

    \n$SYMLINKS_FMT
";

sub main(@){
  die $USAGE if @_ == 1 and $_[0] =~ /^(-h|--help)$/;

  my @commands;

  my @names = @_;
  @names = @SYMLINK_NAMES if @_ == 0;
  for my $name(@names){
    die "$USAGE\n\nunknown symlink name: $name\n" if not defined $SYMLINKS{$name};
    my $sym = $SYMLINKS{$name};

    my $src = "$$sym{src}";
    my $dest = "$$sym{dest}";
    my $destDir = dirname $dest;
    my $cmd = "rmdir $dest 2>/dev/null ; rm -f $dest && ln -s $src $dest";

    my $ipmagicUser;
    if($destDir =~ /^\/home\/(\w+)(?:\/.*)?$/){
      $ipmagicUser = "$1";
    }else{
      $ipmagicUser = "root";
    }

    run "ipmagic", $IPMAGIC_NAME, "-u", $ipmagicUser, "sh -c \"$cmd\"";
  }
}

&main(@ARGV);
