#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";

my @cmds = (
  "mcetool --reset-settings",
  "mcetool --set-dim-timeout=600",
  "mcetool --set-als-autobrightness=disabled",
  "mcetool --set-display-off-single-powerkey-press-actions=unblank,tkunlock",
  "mcetool --set-ps-mode=disabled",
);

sub main(@){
  for my $cmd(@cmds){
    print "$cmd\n";
    system "ipmagic", $ipmagicName, "-u", "root", "mcetool $cmd";
  }
}

&main(@ARGV);
