#!/usr/bin/perl
use strict;
use warnings;

sub createCameraDirs();
sub patchAdvancedCamera();
sub copyGCamXml();

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my $BASE_DIR = `dirname $0 | tr -d '\n'`;
my $GCAM_XML = "$BASE_DIR/backup/gcam-xml/gcam.xml";

my @CAM_DIRS = (
  "/home/$USER/Pictures/Camera",
  "/home/$USER/Videos/Camera",
  "/home/$USER/Videos/Camera/.recording",
  "/home/$USER/Pictures/AdvancedCam",
  "/home/$USER/Videos/AdvancedCam",
  "/home/$USER/Pictures/Screenshots",

  "/media/sdcard/phone/Pictures/Camera",
  "/media/sdcard/phone/Videos/Camera",
  "/media/sdcard/phone/Pictures/AdvancedCam",
  "/media/sdcard/phone/Videos/AdvancedCam",
);

my $ADV_CAM_QML_FILE = "/usr/share/harbour-advanced-camera/qml/pages/CameraUI.qml";
my $ADV_CAM_PATCH = ""
  . "--- CameraUI.qml\n"
  . "+++ /usr/share/harbour-advanced-camera/qml/pages/CameraUI.qml\n"
  . "@@ -583,7 +583,7 @@\n"
  . "         id: mouseFocusArea\n"
  . "         anchors.fill: parent\n"
  . "         z: -1 //Send to back\n"
  . "-        onClicked: {\n"
  . "+        onPressAndHold: {\n"
  . " \n"
  . "             if (settingsOverlay.panelOpen) {\n"
  . "                 settingsOverlay.hideAllPanels()\n"
;

sub main(@){
  createCameraDirs();

  patchAdvancedCamera();

  copyGCamXml();
}

sub createCameraDirs(){
  print "\n\ncreating camera dirs\n";
  my $cmd = "set -x\n";
  $cmd .= "mkdir -p $_\n" foreach @CAM_DIRS;
  system "ipmagic", $IPMAGIC_NAME, "-s", $cmd;
}

sub patchAdvancedCamera(){
  my $tmpPatch = "/tmp/adv-cam-patch";
  print "\n\npatchin adv-cam to use long-press instead of tap to focus\n";
  open FH, "> $tmpPatch" or die "$!\n";
  print FH $ADV_CAM_PATCH;
  close FH;

  system "ipmagic", $IPMAGIC_NAME, "--rsync", "-avP",
    "$tmpPatch",
    ":$tmpPatch";

  system "rm", $tmpPatch;

  system "ipmagic", $IPMAGIC_NAME, "-u", "root", "-s", ""
    . "echo"
    . "  && echo -ne reversing patch: "
    . "  && ( patch --silent -R -f $ADV_CAM_QML_FILE $tmpPatch >/dev/null"
    . "       && echo reversed || echo skipped )"
    . "  && patch -N -f $ADV_CAM_QML_FILE $tmpPatch"
    . "  && rm $tmpPatch"
  ;
}

sub copyGCamXml(){
  my $pkg = "com.shamim.cam";
  my $app = "SGCAM";

  my @apks = grep {-f $_} glob "$BASE_DIR/apks/*_${pkg}_*";
  my $apk;
  if(@apks == 1){
    $apk = $apks[0];
  }else{
    die "ERROR: could not find apk for gcam app $pkg\n";
  }

  my $version;
  if($apk =~ /_${pkg}_(\d+\.\d+\.\d+)/){
    $version = $1;
  }else{
    die "ERROR: could not read MAJ.MIN.PT version from $apk file name\n";
  }

  my $remoteXmlDir = "/home/$USER/android_storage/$app/$version/XML";
  system "ipmagic", $IPMAGIC_NAME, "mkdir", "-p", $remoteXmlDir;

  system "ipmagic", $IPMAGIC_NAME, "--rsync", "-avP", "-L", $GCAM_XML, ":$remoteXmlDir/";

  print "\n\n\n\n#############################\n";
  print "OPEN $app AND DOUBLE-TAP NEAR SHUTTER BUTTON\n\n";
  print "   MAYBE TWICE, CHECK THAT LENS OPTION LABELS CHANGE\n";
}

&main(@ARGV);
