#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

my $IPMAGIC_NAME = "sx";
my $PACKAGE_RESTRICTIONS_XML_FILE = "/home/.android/data/system/users/0/package-restrictions.xml";

my $PACKAGE_RESTRICTIONS = {
  "us.zoom.videomeetings" => ''
    . "    <pkg name=\"us.zoom.videomeetings\">\n"
    . "        <disabled-components>\n"
    . "            <item name=\"us.zoom.videomeetings.SendFileActivity\" />\n"
    . "        </disabled-components>\n"
    . "    </pkg>\n"
};

sub nowMillis();
sub run(@);

sub main(@){
  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  my $nowMillis = 1556995263382;#nowMillis();
  my $tmpPkgRestrictionsFileOld = "/tmp/setup-aliendalvik-$nowMillis-old";
  my $tmpPkgRestrictionsFileNew = "/tmp/setup-aliendalvik-$nowMillis-new";

  run "scp", "root\@$host:$PACKAGE_RESTRICTIONS_XML_FILE", $tmpPkgRestrictionsFileOld;
  run "cp", "-ar", $tmpPkgRestrictionsFileOld, $tmpPkgRestrictionsFileNew;

  if(not -e $tmpPkgRestrictionsFileOld or not -e $tmpPkgRestrictionsFileNew){
    die "error fetching $PACKAGE_RESTRICTIONS_XML_FILE\n";
  }

  my $isChanged = editPackageRestrictions($tmpPkgRestrictionsFileNew);

  print "\n\n\n";
  if($isChanged){
    print "package restrictions changed, updating..\n";
    run "ipmagic", $IPMAGIC_NAME, "-u", "root",
      "systemctl stop aliendalvik.service";

    run "diff", $tmpPkgRestrictionsFileOld, $tmpPkgRestrictionsFileNew;
    run "scp", $tmpPkgRestrictionsFileNew, "root\@$host:$tmpPkgRestrictionsFileNew";
    run "ipmagic", $IPMAGIC_NAME, "-u", "root", "
      cat $tmpPkgRestrictionsFileNew > $PACKAGE_RESTRICTIONS_XML_FILE
      rm $tmpPkgRestrictionsFileNew
    ";
    run "ipmagic", $IPMAGIC_NAME, "-u", "root",
      "systemctl start aliendalvik.service";
  }else{
    print "NO CHANGE to package restrictions\n";
  }

  run "rm", $tmpPkgRestrictionsFileOld;
  run "rm", $tmpPkgRestrictionsFileNew;
}

sub editPackageRestrictions($){
  my ($file) = @_;
  open FH, "< $file" or die "could not read $file\n$!\n";
  my $contents = join '', <FH>;
  close FH;

  my $ws = '(?:\s|\n)*';

  if($contents !~ /
    ^
    ($ws <\?xml\s[^>]*\?> $ws <package-restrictions> $ws)
    (
      (?:
        (?:$ws<pkg[^>]*\/>)
        |
        (?:$ws<pkg[^>]*[^\/]>.*?<\/pkg>)
      )*
    )
    (
      (?: (?:$ws<preferred-activities$ws\/>$ws)
        |
        (?:$ws <preferred-activities$ws>.*?<\/preferred-activities> $ws)
      )?
      (?: (?:$ws<persistent-preferred-activities$ws\/>$ws)
        |
        (?:$ws <persistent-preferred-activities$ws>.*?<\/persistent-preferred-activities> $ws)
      )?
      (?: (?:$ws<crossProfile-intent-filters$ws\/>$ws)
        |
        (?:$ws <crossProfile-intent-filters$ws>.*?<\/crossProfile-intent-filters> $ws)
      )?
      (?: (?:$ws<default-apps$ws\/>$ws)
        |
        (?:$ws <default-apps$ws>.*?<\/default-apps> $ws)
      )?

      $ws <\/package-restrictions> $ws
    )
    $/sxi){
    die "ERROR: malformed $PACKAGE_RESTRICTIONS_XML_FILE\n";
  }
  my ($prefix, $pkgXml, $suffix) = ($1, $2, $3, $4);

  my @pkgs = $pkgXml =~ /
    (
      (?:$ws<pkg[^>]*\/>)
      |
      (?:$ws<pkg[^>]*[^\/]>.*?<\/pkg>)
    )
  /gsxi;
  if($pkgXml ne join("", @pkgs)){
    die "ERROR: malformed <pkg> tags in $PACKAGE_RESTRICTIONS_XML_FILE\n";
  }

  my $isChanged = 0;

  for my $pkg(@pkgs){
    my $pkgName = $1 if $pkg =~ /<pkg name="([^"]+)"/;
    die "malformed package: $pkg\n" if not defined $pkgName;

    if(defined $$PACKAGE_RESTRICTIONS{$pkgName}){
      my $oldPkg = $pkg;
      my $newPkg = $$PACKAGE_RESTRICTIONS{$pkgName};

      my $oldPkgTrim = $oldPkg;
      $oldPkgTrim =~ s/^$ws//sxi;
      $oldPkgTrim =~ s/$ws$//sxi;

      my $newPkgTrim = $newPkg;
      $newPkgTrim =~ s/^$ws//sxi;
      $newPkgTrim =~ s/$ws$//sxi;

      my ($wsPrefix, $wsSuffix) = ($1, $2) if $pkg =~ /^($ws).*?($ws)$/sxi;
      $newPkg = "$wsPrefix$newPkgTrim$wsSuffix";

      if($oldPkgTrim ne $newPkgTrim){
        print "PACKAGE RESTRICTION UPDATED:\n=====\n$oldPkgTrim\n=>\n=====\n$newPkgTrim\n";
        $pkg = $newPkg;
        $isChanged = 1;
      }
    }
  }

  $pkgXml = join("", @pkgs);

  $contents = $prefix . $pkgXml . $suffix;

  if($isChanged){
    open FH, "> $file" or die "could not write $file\n$!\n";
    print FH $contents;
    close FH;
  }

  return $isChanged;
}

sub nowMillis(){
  return int(time * 1000.0 + 0.5);
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
