#!/usr/bin/perl
use strict;
use warnings;
use File::Basename qw(basename);

my $IPMAGIC_NAME = "sx";
my $USER = "nemo";

my $EXEC = basename $0;

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message

  $EXEC
    setup ssh
";

sub main(@){
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  print "setup sshc $USER\n";
  system "sshc", "--close", "$USER\@$host";
  system "sshc", "$USER\@$host", "echo ok $USER";

  print "enable ssh root login\n";
  system "sshc", "$USER\@$host", 'su -c "
    sed -i \"s/^\s*#*\s*PermitRootLogin\s.*/PermitRootLogin yes/\" /etc/ssh/sshd_config;
    sed -i \"s/^\s*#*\s*GatewayPorts\s.*/GatewayPorts yes/\" /etc/ssh/sshd_config;
    systemctl restart sshd;
  "';

  print "sleep 3s\n";
  sleep 3;

  print "setup sshc root\n";
  system "sshc", "--close", "root\@$host";
  system "sshc", "root\@$host", "echo ok root";

  print "ssh-keygen\n";
  system "sshc", "$USER\@$host", "
    set -x
    if [ ! -f ~/.ssh/$host.pub ]; then
      ssh-keygen -f ~/.ssh/id_rsa -N '' -t rsa
      mv ~/.ssh/id_rsa.pub ~/.ssh/$host.pub
    fi
  ";

  print "create root ssh dir\n";
  system "sshc", "root\@$host", "
    set -x
    mkdir -p /root/.ssh/
  ";

  print "fetch pubkey\n";
  system "sshc", "--scp", "$USER\@$host:/home/$USER/.ssh/$host.pub", "$ENV{HOME}/.ssh/$host.pub";

  print "run pubkeys\n";
  system "pubkeys", "$IPMAGIC_NAME", "scp";
  system "pubkeys", "$IPMAGIC_NAME-root", "scp";

  print "set perms on ssh config\n";
  system "ipmagic", $IPMAGIC_NAME, "-u", $USER, "touch /home/$USER/.ssh/config";
  system "ipmagic", $IPMAGIC_NAME, "-u", $USER, "chmod 655 /home/$USER/.ssh/config";

  print "cleanup\n";
  system "sshc", "--close", "$USER\@$host";
  system "sshc", "--close", "root\@$host";
}

&main(@ARGV);
