#!/usr/bin/perl
use strict;
use warnings;
use lib `dirname $0 | tr -d '\n'`;
use PhoneBackupUtils;

my $IPMAGIC_NAME = "sx";

my @TRACKER_INDEX_DIRS = qw(
  /media/sdcard/droid/DCIM/AndroidCamera/
  /media/sdcard/phone/Pictures/Camera/
  /media/sdcard/phone/Videos/Camera/
);

sub main(@){

  for my $dir(@TRACKER_INDEX_DIRS){
    run "ipmagic", $IPMAGIC_NAME, "-s", "localsearch", "index", "--add", $dir;
  }
}


&main(@ARGV);
