#!/usr/bin/perl
use strict;
use warnings;

my $srcBGDir = "$ENV{HOME}/.cache/backgrounds";
my $sdcardDestBGDir = "/media/sdcard/phone/Backgrounds";
my $finalDestBGDir = "/home/nemo/Backgrounds";


my @bgDirNames = qw(sx sx-ambience sx-ambience-full sx-ambience-small);

my $ipmagicName = "sx";

my $user = "nemo";

sub run(@);

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  run "ipmagic", $ipmagicName, "-u", $user, "mkdir -p $sdcardDestBGDir";
  run "ipmagic", $ipmagicName, "-u", $user, "mkdir -p $finalDestBGDir";

  #local => sdcard
  for my $bgDirName(@bgDirNames){
    run "rsync", "-avP", "--del", "--no-owner", "--no-group",
      "$srcBGDir/$bgDirName/", "$user\@$host:$sdcardDestBGDir/$bgDirName/";
  }

  #sdcard => internal
  run "ipmagic", $ipmagicName, "-u", $user,
    "rsync -avP --del $sdcardDestBGDir/ $finalDestBGDir/";
}

sub run(@){
  print "@_\n";
  system @_;
  die "\"@_\" failed\n" if $? != 0;
}

&main(@ARGV);
