#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

my $IPMAGIC_NAME = "sx";

my $STARTUP_SCRIPT_FILE = "/usr/local/bin/autostart";
my $STARTUP_SCRIPT_CONTENTS = "#!/bin/sh
PATH=/home/nemo/bin:\$PATH

/home/nemo/bin/screen-daemon remount-sdcard --start

SD_PHONE_MNT=`sudo lsblk /dev/mmcblk0p1 -n -o MOUNTPOINT`
SD_DROID_MNT=`sudo lsblk /dev/mmcblk0p2 -n -o MOUNTPOINT`

sudo mkdir -p /media/sdcard/
sudo rm -f /media/sdcard/phone
sudo ln -s \$SD_PHONE_MNT /media/sdcard/phone
sudo rm -f /media/sdcard/droid
sudo ln -s \$SD_DROID_MNT /media/sdcard/droid

/home/nemo/bin/screen-daemon button-monitor --start
/home/nemo/bin/screen-daemon keepalive --start
/home/nemo/bin/screen-daemon mpris-fakeplayer --start
/home/nemo/bin/screen-daemon lock-daemon --start

sudo cpu-enable fast

bluetooth-fix
";

my @SYSTEMD_SYMLINKS = qw(
  /home/nemo/.config/systemd/user/auto-start.service
  /home/nemo/.config/systemd/user/user-session.target.wants/auto-start.service
);

my $SYSTEMD_SERVICE_FILE = "/usr/lib/systemd/user/auto-start.service";
my $SYSTEMD_SERVICE_CONTENTS = "[Unit]
Description=Auto-start stuff after lipstick
Requires=lipstick.service
After=lipstick.service

[Service]
Type=oneshot
ExecStart=$STARTUP_SCRIPT_FILE
RemainAfterExit=yes

[Install]
WantedBy=user-session.target
";

sub writeRemoteFile($$$$);
sub run(@);

sub main(@){
  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  writeRemoteFile $host, "root", $STARTUP_SCRIPT_FILE, $STARTUP_SCRIPT_CONTENTS;
  run "ssh", "root\@$host", "
    chmod a+x $STARTUP_SCRIPT_FILE
    chown root.root $STARTUP_SCRIPT_FILE
  ";

  writeRemoteFile $host, "root", $SYSTEMD_SERVICE_FILE, $SYSTEMD_SERVICE_CONTENTS;
  run "ssh", "root\@$host", "
    chown nemo.nemo $SYSTEMD_SERVICE_FILE
  ";

  for my $symlink(@SYSTEMD_SYMLINKS){
    run "ssh", "nemo\@$host", "
      mkdir -p `dirname $symlink`
      rm -f $symlink
      ln -s $SYSTEMD_SERVICE_FILE $symlink
    ";
  }
}

sub writeRemoteFile($$$$){
  my ($host, $userName, $destFile, $contents) = @_;
  my $tmpFile = "/tmp/$0-" . int(time * 1000.0);
  open FH, "> $tmpFile" or die "Could not write to $tmpFile\n";
  print FH $contents;
  close FH;
  run "rsync", "-avP", $tmpFile, "$userName\@$host:$destFile";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
