#!/usr/bin/perl
use strict;
use warnings;

my $srcBGDir = "$ENV{HOME}/.cache/backgrounds";
my $destBGDir = "/home/nemo/Backgrounds";
my @bgDirNames = qw(sx sx-ambience sx-ambience-full sx-ambience-small);

my $ipmagicName = "sx";

sub run(@);

sub main(@){
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  run "ipmagic", $ipmagicName, "-u", "root", "mkdir -p $destBGDir";

  for my $bgDirName(@bgDirNames){
    run "rsync", "-avP", "--del", "--no-owner", "--no-group",
      "$srcBGDir/$bgDirName/", "root\@$host:$destBGDir/$bgDirName/";
  }
}

sub run(@){
  print "@_\n";
  system @_;
  die "\"@_\" failed\n" if $? != 0;
}

&main(@ARGV);
