#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(time);

my $IPMAGIC_NAME = "sx";

my $VENDOR_MIXER_XML = "/vendor/etc/mixer_paths.xml";

sub run(@);

sub main(@){
  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  my $nowMillis = int(time * 1000.0 + 0.5);

  my $xmlTmpFile = '/tmp/vendor-mixer-xml-1655774524';#"/tmp/vendor-mixer-xml-$nowMillis";
  run "rsync", "-avP", "root\@$host:$VENDOR_MIXER_XML", $xmlTmpFile;

  my $patchTmpFile = "/tmp/vendor-mixer-patch-$nowMillis";
  open FH, "> $patchTmpFile" or die "ERROR: could not write $patchTmpFile\n$!\n";
  print FH getPatch();
  close FH;

  run "patch", "-N", $xmlTmpFile, $patchTmpFile;
  my $exitCode = $?;
  if($exitCode != 0){
    print "\npatch failed, attempting to reverse + re-apply\n";
    run "patch", "-R", $xmlTmpFile, $patchTmpFile;
    $exitCode = $?;
    if($exitCode != 0){
      die "ERROR: patch failed\n";
    }

    print "\nre-applying patch\n";
    run "patch", "-N", $xmlTmpFile, $patchTmpFile;
    $exitCode = $?;
    if($exitCode != 0){
      die "ERROR: patch failed\n";
    }
  }

  print "\nmixer xml file patched successfully, backing up orig and overwriting\n";
  run "ipmagic", $IPMAGIC_NAME, "-u", "root",
    "cp -ar $VENDOR_MIXER_XML $VENDOR_MIXER_XML.bak.$nowMillis\n";

  run "rsync", "-avP", $xmlTmpFile, "root\@$host:$VENDOR_MIXER_XML";
}

sub getPatch(){
return '
***************
*** 344,351 ****
      <ctl name="DEC4 Volume" value="84" />
      <ctl name="DEC5 Volume" value="84" />
      <ctl name="DEC6 Volume" value="84" />
!     <ctl name="DEC7 Volume" value="84" />
!     <ctl name="DEC8 Volume" value="84" />
  
      <!-- Compander controls -->
      <ctl name="COMP1 Switch" value="1" />
--- 344,351 ----
      <ctl name="DEC4 Volume" value="84" />
      <ctl name="DEC5 Volume" value="84" />
      <ctl name="DEC6 Volume" value="84" />
!     <ctl name="DEC7 Volume" value="94" />
!     <ctl name="DEC8 Volume" value="94" />
  
      <!-- Compander controls -->
      <ctl name="COMP1 Switch" value="1" />
***************
*** 1818,1829 ****
  
      <!-- Gain offset target for dmic1 unit calibration -->
      <path name="dmic1-adj-gain">
!         <ctl name="DEC7 Volume" value="94" />
      </path>
  
      <!-- Gain offset target for dmic2 unit calibration -->
      <path name="dmic2-adj-gain">
!         <ctl name="DEC8 Volume" value="94" />
      </path>
  
      <!-- For Tavil, DMIC numbered from 0 to 5 -->
--- 1818,1829 ----
  
      <!-- Gain offset target for dmic1 unit calibration -->
      <path name="dmic1-adj-gain">
!         <ctl name="DEC7 Volume" value="114" />
      </path>
  
      <!-- Gain offset target for dmic2 unit calibration -->
      <path name="dmic2-adj-gain">
!         <ctl name="DEC8 Volume" value="104" />
      </path>
  
      <!-- For Tavil, DMIC numbered from 0 to 5 -->
***************
*** 2070,2077 ****
  
      <path name="stereo-mic">
          <path name="stereo-mic-common" />
!         <ctl name="DEC8 Volume" value="86" />
!         <ctl name="DEC7 Volume" value="90" />
      </path>
  
      <path name="speaker-mono-mic-common">
--- 2070,2077 ----
  
      <path name="stereo-mic">
          <path name="stereo-mic-common" />
!         <ctl name="DEC8 Volume" value="96" />
!         <ctl name="DEC7 Volume" value="100" />
      </path>
  
      <path name="speaker-mono-mic-common">
***************
*** 2081,2087 ****
  
      <path name="speaker-mono-mic">
          <path name="speaker-mono-mic-common" />
!         <ctl name="DEC7 Volume" value="92" />
      </path>
  
      <path name="speaker-protected">
--- 2081,2087 ----
  
      <path name="speaker-mono-mic">
          <path name="speaker-mono-mic-common" />
!         <ctl name="DEC7 Volume" value="102" />
      </path>
  
      <path name="speaker-protected">
***************
*** 2243,2250 ****
  
      <path name="headset-mic">
          <path name="amic2" />
!         <ctl name="DEC0 Volume" value="84" />
!         <ctl name="ADC2 Volume" value="11" />
      </path>
  
      <path name="headset-mic-asr">
--- 2243,2250 ----
  
      <path name="headset-mic">
          <path name="amic2" />
!         <ctl name="DEC0 Volume" value="110" />
!         <ctl name="ADC2 Volume" value="19" />
      </path>
  
      <path name="headset-mic-asr">
***************
*** 2442,2449 ****
  
      <path name="voice-rec-mic">
          <path name="camcorder-mic-common" />
!         <ctl name="DEC8 Volume" value="86" />
!         <ctl name="DEC7 Volume" value="90" />
      </path>
  
      <path name="camcorder-mic">
--- 2442,2449 ----
  
      <path name="voice-rec-mic">
          <path name="camcorder-mic-common" />
!         <ctl name="DEC8 Volume" value="96" />
!         <ctl name="DEC7 Volume" value="100" />
      </path>
  
      <path name="camcorder-mic">
***************
*** 2516,2522 ****
          <ctl name="ADC MUX7" value="AMIC" />
          <ctl name="AMIC MUX7" value="ADC4" />
          <!-- 67 % of 124 (range 0 - 124) Register: 0x221 -->
!         <ctl name="DEC7 Volume" value="83" />
          <!-- 47 % of 19 (rounded) register: 0x169 -->
          <ctl name="ADC4 Volume" value="6" />
          <!-- SLIM TX8 records for right channel -->
--- 2516,2522 ----
          <ctl name="ADC MUX7" value="AMIC" />
          <ctl name="AMIC MUX7" value="ADC4" />
          <!-- 67 % of 124 (range 0 - 124) Register: 0x221 -->
!         <ctl name="DEC7 Volume" value="93" />
          <!-- 47 % of 19 (rounded) register: 0x169 -->
          <ctl name="ADC4 Volume" value="6" />
          <!-- SLIM TX8 records for right channel -->
';
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
