#!/usr/bin/perl
use strict;
use warnings;

my $targetSize = "1920x1080";

my $localDCIM = "$ENV{HOME}/Code/sx/backup/DCIM";
my $localPixmirror = "$ENV{HOME}/Code/sx/backup/DCIM-pixmirror";

my $remotePixmirror = "/media/sdcard/phone/DCIM-pixmirror";
my $remoteSym = "/home/nemo/pixmirror";

sub run(@);

sub main(@){
  my $host = `sx`;
  chomp $host;

  print "\n\n=====making pixmirror remote dirs\n";
  run "sx", "
    mkdir -p $remotePixmirror
    rm -f $remoteSym
    ln -s $remotePixmirror $remoteSym
  ";

  print "\n\n=====running pixmirror locally\n";
  run "pixmirror", "--size=$targetSize", "--orient", $localDCIM, $localPixmirror;

  print "\n\n=====syncing pixmirror local=>remote\n";
  run "rsync", "-avP", "--del",
    "$localPixmirror/",
    "nemo\@$host:$remotePixmirror";
  run "sx", "symlink-pixmirror";
}

sub run(@){
  print "@_\n";
  system @_;
  die "FAILED: \"@_\"\n" if $? != 0;
}

&main(@ARGV);
