#!/usr/bin/perl
use strict;
use warnings;

my $ipmagicName = "sx";
my $user = "nemo";

my @HOME_RSYNC_FILES = qw(
  .bashrc
  .gitconfig
  .gpg
  .secrets
  .vimrc

  .config/qtemail/
  .vim/
);

my @INITIAL_USER_CMDS = (
);
my @FINAL_USER_CMDS = (
);

my @INITIAL_ROOT_CMDS = (
  "rmdir /root/bin 2>/dev/null",
  "rm -f /root/bin",
  "ln -s /home/$user/bin/ /root/bin",
);
my @FINAL_ROOT_CMDS = (
  "sed -i 's/›/>/g' /home/$user/.vimrc",
  "sed -i 's/›/>/g' /root/.vimrc",
);

my @SPECIAL_RSYNCS = (
);

my $USRLOCALBIN_LOCAL_DIR = "$ENV{HOME}/install/root-files/usr/local/bin";
my $USRLOCALBIN_REMOTE_DIR = "/usr/local/bin";
my @USRLOCALBIN_EXECS = qw(
  alarm
  ipmagic
  term
  vpn
);

my $HOMEBIN_LOCAL_DIR = "$ENV{HOME}/bin";
my $HOMEBIN_REMOTE_DIR = "/home/nemo/bin";
my @HOMEBIN_EXECS = qw(
  alert
  ddrname
  display-guess
  escribe-hosts
  gpg-sym
  lirr_train_time
  loop
  pidgin-logs
  pix
  revtun
  sb-rt-status
  sbcam
  scoreddr
  screen-cmd
  screen-daemon
  seedbox
  speedtest
  transmission-webui
);

sub run(@);

sub main(@){
  die "Usage: $0\n" if @_ > 0;
  my $host = `ipmagic $ipmagicName`;
  chomp $host;

  for my $cmd(@INITIAL_USER_CMDS){
    run "ipmagic", $ipmagicName, "-u", $user, $cmd;
  }
  for my $cmd(@INITIAL_ROOT_CMDS){
    run "ipmagic", $ipmagicName, "-u", "root", $cmd;
  }

  my @usrlocalbinFiles = map {"$USRLOCALBIN_LOCAL_DIR/$_"} @USRLOCALBIN_EXECS;
  run "rsync", "-avP", @usrlocalbinFiles, "root\@$host:$USRLOCALBIN_REMOTE_DIR/";

  my @homebinFiles = map {"$HOMEBIN_LOCAL_DIR/$_"} @HOMEBIN_EXECS;
  run "rsync", "-avP", @homebinFiles, "$user\@$host:$HOMEBIN_REMOTE_DIR/";

  for my $file(@HOME_RSYNC_FILES){
    run "rsync", "-avP", "$ENV{HOME}/$file", "$user\@$host:~/$file";
    run "rsync", "-avP", "$ENV{HOME}/$file", "root\@$host:~/$file";
  }

  for my $rsync(@SPECIAL_RSYNCS){
    my ($src, $dest) = @$rsync;
    run "rsync", "-avP", $src, "$user\@$host:$dest";
  }

  for my $cmd(@FINAL_USER_CMDS){
    run "ipmagic", $ipmagicName, "-u", $user, $cmd;
  }
  for my $cmd(@FINAL_ROOT_CMDS){
    run "ipmagic", $ipmagicName, "-u", "root", $cmd;
  }
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
