#!/usr/bin/perl
use strict;
use warnings;

my $IPMAGIC_NAME = "sx";
my $IPMAGIC_USER = "nemo";

my $DIR_BASE = "$ENV{HOME}/Code/sx";
my $DIR_BACKUP = "$DIR_BASE/backup";

my $DIR_REMOTE_SHARED_PREFS = "/opt/alien/data/data/im.vector.alpha/shared_prefs";

my $usage = "Usage:
  $0 --backup
    copy shared_prefs remote => backup

  $0 --restore
    copy shared_prefs backup => remote
    set uid/gid to android app user id
";

sub nowMillis();
sub run(@);

sub main(@){
  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  if(@_ == 1 and $_[0] =~ /^(--backup)$/){
    my $nowSex = time;
    my $nowYMD = `date --date=\@$nowSex +'%Y-%m-%d'`;
    chomp $nowYMD;

    my $destDirName = "shared_prefs-${nowYMD}_${nowSex}";

    my $destDir = "$DIR_BACKUP/backup-riot/$destDirName";
    run "rsync", "-avP", "root\@$host:$DIR_REMOTE_SHARED_PREFS/", "$destDir/";

    run "rm", "-f", "$DIR_BACKUP/backup-riot/shared_prefs-latest";
    run "ln", "-s", $destDirName, "$DIR_BACKUP/backup-riot/shared_prefs-latest";
  }elsif(@_ == 1 and $_[0] =~ /^(--restore)$/){
    my $srcDir = "$DIR_BACKUP/backup-riot/shared_prefs-latest";
    my $appUserId = `ipmagic $IPMAGIC_NAME -u root stat -c %u $DIR_REMOTE_SHARED_PREFS`;
    chomp $appUserId;
    if($appUserId !~ /^\d+$/){
      die "could not read android app user ID\n";
    }elsif($appUserId =~ /^(0|1000|100000)$/){
      die "app user id ($appUserId) should never be 0 or 1000 or 100000\n";
    }
    run "rsync", "-avP", "--del", "$srcDir/", "root\@$host:$DIR_REMOTE_SHARED_PREFS/";
    run "ipmagic", $IPMAGIC_NAME, "-u", "root",
      "chown", "-R", "$appUserId.$appUserId", $DIR_REMOTE_SHARED_PREFS;
  }else{
    die $usage;
  }
}

sub nowMillis(){
  return int(time * 1000.0 + 0.5);
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
